### ISSUE TITLE
Start script exception

### ISSUE THREAD

**Issue by andreabat** [trobz/docker-odoo#1]
Hi,
when launching the image this is what I get before it exits:

   INFO: First run, initalize the container...
   INFO: Create user openerp with UID: 1000, GID: 1000, home path: /opt/openerp
SUCCESS: User openerp configured
   WARN: Please, run this image with your public SSH key mounted on /usr/local/ssh/id_rsa.pub
SUCCESS: SSH Server daemon configured
   INFO: Config supervisor with openerp, HTTP access enabled on port 8011
SUCCESS: Supervisord process manager configured
/usr/local/docker/start/init/06_vim.sh: line 16: syntax error: unexpected end of file

.

I am running the container with this command:

```
        docker run -p 8069:8069 -p 5433:5432 -p 8011:8011 -v /root/config:/etc/postgresql/docker/config -v /root/data:/etc/postgresql/docker/data -v /root/log:/etc/postgresql/docker/log --name odoo trobz/odoo
```

**Comment by zazabe** [comment]
Hi, 

I think it's fixed in the latest version, a stupid mistake in [this script](https://github.com/trobz/docker-sshd/blob/master/scripts/start/init/06_vim.sh)...

by the way, thanks for testing, we are doing some tests on our side too, before communicating on these docker images :)
