### ISSUE TITLE
Installation script ubuntu14.04

### ISSUE THREAD

**Issue by belcboo** [trobz/docker-odoo#9]
Hi,

Im trying to use the script to do the installation, but when I try to do the installation on a clean ubuntu using the command: curl -sSL http://code.trobz.com/install/latest  | /bin/bash I get the error: "Hi young Trobzer, here we share only public files, snippets, bunch of scripts, etc...", can somebody help me please?

Thanks!

**Comment by thuandt** [comment]
Sorry but for now we're stop maintaince this repository.

**Comment by belcboo** [comment]
:( okay, 

Thank you sir!
